'use strict';mix_d("P13NSCCards__p13n-rvi:p13n-rvi__BDtsjEh4","exports tslib @p/A @c/metrics @c/aui-carousel @c/dom @c/remote-operations @c/scoped-dom @p/a-carousel-framework @c/logger @c/aui-untrusted-ajax @c/browser-operations".split(" "),function(H,q,P,C,Q,R,S,T,U,V,W,X){function x(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var p=x(P),Y=x(Q),I=x(S),v=x(T),Z=x(U),z=x(V),aa=x(W),ba=x(X),J={},D=function(a,e,b){void 0===e&&(e="");void 0===b&&(b=1);e=a+e;J.hasOwnProperty(e)||(J[e]=
!0,C.count(a,(C.count(a)||0)+b))},ca=function(a){D(p["default"].capabilities.mobile?"Card:EERU:SharedLib:mobile:render":"Card:EERU:SharedLib:desktop:render");var e=function(d,c){d={$event:{preventDefault:p["default"].$.noop,stopPropagation:p["default"].$.noop},$target:d.getContent().find('[data-a-tab-name="'+c+'"]'),data:{name:"energyEfficiencyTabSet"}};p["default"].trigger("a:declarative:a-tabs:click",d)},b=function(d,c){var f=d&&d.$event,h=d&&d.data||{},k=h.activeTabName,l=h.modalHeight,r=h.name;
f&&f.preventDefault&&f.preventDefault();f&&f.stopPropagation&&f.stopPropagation();f=c.get(r);f||(p["default"].on("a:popover:beforeShow:"+r,function(g){g.popover&&g.popover.getContent&&(g=g.popover.getContent(),g.find(".a-manually-loaded").parent().css("min-height",l),p["default"].loadDescendantImagesManually(g))}),f=c.create(d.$target,h));f.show();e(f,k)};a.when("a-secondary-view").execute("RegisterEnergyEfficiencyEventMobile",function(d){p["default"].declarative("card-energy-efficiency-secondary-view",
"click",function(c){D("Card:EERU:SharedLib:mobile:click",c&&c.data&&c.data.name||"");b(c,d)})});a.when("a-modal").execute("RegisterEnergyEfficiencyEventDesktop",function(d){p["default"].declarative("card-energy-efficiency-modal","click",function(c){D("Card:EERU:SharedLib:desktop:click",c&&c.data&&c.data.name||"");b(c,d)})})},da=function(a){a.when("ready").execute("EEBadgeProductFicheResize",function(e){var b=p["default"].$;b(".energyEfficiencyContainer").each(function(d,c){d=b(c).find(".energyEfficiencyProductFicheLabel").first();
c=b(c).find("svg").first();d.parent().outerHeight()>c.outerHeight()&&(d.removeClass("a-size-small"),d.addClass("a-size-micro"),d.parent().outerHeight()>c.outerHeight()&&d.parent().css("line-height","10px"))})})},ea=function(){var a=window.P;ca(a);da(a)},fa={ctiList:["Website/Personalization/Report a Problem CX"],category:"Website",type:"Personalization",item:"Report a Problem CX",folder:"9c9c97c9-6f69-4dba-a55d-26045c6a3068",group:"P13N Report a Problem CX"},ha=[{ctiList:["Website/Personalization/Similarities",
"Website/Detail Page/Similarities"],category:"Website",type:"Personalization",item:"Similarities",folder:"4d16d05d-9a17-4b36-b8fe-9ee159ff81de",group:"Similarities"}],la=function(a){var e=v["default"].cardRoot.querySelector(".p13n-report-flag"),b=ba["default"].setup();b.define("showFlag","mouseover",function(){e.classList.remove("p13n-report-flag-hide")});b.define("hideFlag","mouseout",function(){e.classList.add("p13n-report-flag-hide")});b.attach("showFlag",a);b.attach("hideFlag",a);var d=v["default"].cardRoot.querySelector(".internal-flag-form"),
c=d.querySelector(".internal-flag-env-data").dataset,f=d.querySelector(".internal-flag-title-text"),h=d.querySelector(".internal-flag-description").firstElementChild,k=d.querySelector(".internal-flag-alias"),l=d.querySelector(".internal-flag-response-message"),r=function(g){g.preventDefault();g=function(t){return!t||!t.trim()};if(g(f.value)||g(h.value)||g(k.value))return E(l,!1,"Something went wrong. One of the required fields was missing."),!1;g=v["default"].cardRoot.querySelectorAll(".a-dynamic-image");
var m;if(m=v["default"].cardRoot.querySelector(".a-carousel-heading")){var u=ia(a,g.length);m="Internal user reported issue '"+f.value+"' with widget: "+m.innerText}else u=ja(a),m="Internal user reported issue '"+f.value+"'";g=ka(g,u,h.value,k.value,c);var n=fa;ha.forEach(function(t){t.ctiList.includes(c.cti)&&(n=t)});aa["default"].post("https://p13ngoals.corp.amazon.com/sims",{accepts:"text/html, application/json",contentType:"application/json;charset=UTF-8"},{sim_params:{assigned_folder:n.folder,
description:g,descriptionContentType:"text/amz-markdown-sim",extensions:{tt:{assignedGroup:n.group,category:n.category,impact:5,item:n.item,type:n.type}},tags:[{id:"internal-problem-generated"}],title:m}}).then(function(t){E(l,!0,t)}).catch(function(t){E(l,!1,t)});return!1};d.onsubmit=function(g){return r(g)};b=v["default"].cardRoot.querySelector(".p13n-desktop-report-problem-flag-data");if(b.dataset.name)p["default"].on("a:popover:hide:"+b.dataset.name,function(){d.reset();l.innerText=""})},ia=function(a,
e){if(!a.dataset.aCarouselOptions)return z["default"].log("Empty ASIN List in carouselElement.dataset.aCarouselOptions","ERROR"),[];a=JSON.parse(a.dataset.aCarouselOptions).ajax.id_list;var b=v["default"].cardRoot.querySelector(".a-carousel-firstvisibleitem");b=(Number(b.value)||1)-1;return a.map(function(d){return JSON.parse(d).id}).slice(b,b+e)},ja=function(a){return(a=a.dataset.asinList)?a.split(","):[]},ka=function(a,e,b,d,c){for(var f="",h=0;h<a.length;h++){var k=a[h];f+=(k?"![]("+k.src+")":
"IMAGE MISSING")+"\nASIN: "+(e[h]?e[h]:"ASIN MISSING")+"\n\n"}return"**This SIM-T ticket is created by the 'Report a Problem' internal tool. To know more, here's its wiki: https://w.amazon.com/bin/view/Personalization/CoreRecommendations/Projects/Canaries/Report-a-Problem-UX-on-P13NWidget/UserGuide/**\n\n**Alias:** ["+(d+"](https://phonetool.amazon.com/users/"+d+")\n**Comment:** "+b+"\n\n**Widget Group ID:** "+c.widgetGroupId+"\n**Strategy ID:** "+c.strategyId+"\n**CTI:** "+c.cti+"\n**Facets:** ")+
(c.facets+"\n**Content Reftag:** "+c.reftag+"\n"+(""!==c.baseAsin?"**Page ASIN:** "+c.baseAsin+"\n":"")+"\n**SessionID:** ")+(c.sessionId+"\n**MarketplaceID:** "+c.marketplaceId+"\n**Device Type:** "+c.deviceType+"\n\n**List of ASINs:**\n\n")+f},E=function(a,e,b){e?(a.classList.remove("a-color-error"),b.responseBody&&"object"===typeof b.responseBody?b.responseBody.response&&b.responseBody.response.id?a.innerHTML="Success, here's the <a href=\"https://t.corp.amazon.com/"+b.responseBody.response.id+
'" target="_blank">SIM-T ticket</a> you created.':(z["default"].log("Fail to find the id of the SIM-T ticket created in the response body of response data.","ERROR"),a.innerText="Success, but we could not find the link to the SIM-T ticket."):(z["default"].log("The response body of response data is not an object.","ERROR"),a.innerText="Success, but we could not find the link to the SIM-T ticket.")):(a.classList.add("a-color-error"),a.innerText="string"===typeof b?b:"Oops! Something went wrong. Please try again.")},
ma={setupModal:function(a){return q.__awaiter(void 0,void 0,void 0,function(){var e;return q.__generator(this,function(b){e=v["default"].cardRoot.querySelector(".p13n-report-problem-modal-root");if(!e)return[2];la(a);return[2]})})}},na=I["default"].setup(["getLazyLoadDeliveryMessage"]),oa=function(a){return q.__awaiter(void 0,void 0,void 0,function(){var e,b,d;return q.__generator(this,function(c){switch(c.label){case 0:e=a.querySelectorAll("[data-udm-asin]:not([data-requested=true])");if(!e.length)return[2,
void 0];b=[];e.forEach(function(f){var h=f.dataset.udmAsin,k=f.dataset.udmMerchantId,l=f.dataset.udmBlockSize,r=f.dataset.udmLayoutSize,g="true"===f.dataset.udmBadgeWithoutProgramName;h&&k&&l&&(b.push({asin:h,merchantId:k,blockSize:l,layoutSize:r,badgeWithoutProgramName:g}),f.dataset.requested="true")});return b.length?[4,na.getLazyLoadDeliveryMessage({lazyLoadDeliveryMessageViewModels:b})]:[2,void 0];case 1:return d=c.sent(),[2,[].slice.call(d.querySelectorAll("[data-udm-asin]:not([data-requested=true])"))]}})})},
pa=function(a){return q.__awaiter(void 0,void 0,void 0,function(){var e;return q.__generator(this,function(b){switch(b.label){case 0:return[4,oa(a)];case 1:e=b.sent();if(!e)return[2];e.map(function(d){var c=d.dataset.udmAsin,f=d.dataset.udmMerchantId;c&&f&&(c=a.querySelector('[data-udm-asin="'+c+'"][data-udm-merchant-id='+f+"]"))&&(c.outerHTML=d.innerHTML)});return[2]}})})},K=[],qa=function(a){var e=Array.prototype.slice.call(a.querySelectorAll("[data-metrics]"));e.push(a);e.forEach(function(b){if(b&&
b.dataset&&b.dataset.metrics&&(!b.id||!K.includes(b.id))){var d=JSON.parse(b.dataset.metrics),c;for(c in d)d.hasOwnProperty(c)&&C.count(c,d[c]);b.removeAttribute("data-metrics");b.id&&K.push(b.id)}})},L=/(?=[ \-\/])|(?=[\u3105-\u312F])|(?=[\u31A0-\u31BA])|(?=[\u4E00-\u9FD5])|(?=[\u3400-\u4DB5])|(?=[\uF900-\uFAFF])|(?=[\u3040-\u309F])|(?=[\u30A0-\u30FF])|(?=[\u3190-\u319F])/,M=/[^\/\-\[\]():\s]/,ra=function(a){var e=p["default"].$("<div>")[0];e.classList.add("p13n-sc-offscreen-truncate");var b=parseInt(a.getAttribute("data-rows")||
"2",10),d=function(){var h=a.innerHTML;a.innerHTML="&hellip;";var k=a.clientHeight;a.innerHTML=h;return k}();if(b){if(d){var c=function(h){e.innerHTML=h;return Math.round(e.clientHeight/d)<=b},f=function(h,k){h=h.split(k);var l=Math.floor(a.clientWidth/12),r=function(m){e.classList.add("p13n-sc-offscreen-truncate");e.style.overflow="hidden";e.textContent=m;a.appendChild(e);m=a.clientWidth>=a.scrollWidth;a.removeChild(e);return m},g=function(m){var u=m.length-l;m.trim().length>l&&!r(m)&&Array.prototype.slice.call(m).map(function(n,
t){return t>l&&t<=u&&M.test(n)?"&shy;"+n:n});return m};return h.map(function(m){return g(m)}).join("")};return{truncate:function(){var h=a.innerHTML.trim(),k=a.textContent||"";h=f(h,L);a.appendChild(e);if(c(h))a.removeChild(e),a.innerHTML=h;else{var l=h.split(L);for(var r=1,g=l.length,m,u,n=0;r!==g;)if(m=Math.floor((g+r)/2),u=l.slice(0,m).join("")+"&hellip;",c(u)){if(1>=g-m){for(n=m;0<n&&!M.test(l[n-1]);)n--;break}r=m}else g=m;l=0===n?void 0:l.slice(0,n).join("")+"&hellip;";l?(a.innerHTML=l,a.setAttribute("title",
k),a.setAttribute("aria-label",k)):(z["default"].log("Unable to successfully truncate line "+h,"ERROR"),a.removeChild(e))}}}}z["default"].log("Truncation element does not have a line height or it is zero","ERROR")}else z["default"].log("Truncation element missing necessary line number data","ERROR")},sa=function(a){var e=Array.prototype.slice.call(a.getElementsByClassName("p13n-sc-truncate"));a=a.getElementsByClassName("p13n-sc-truncate-fallback");(window.CSS&&CSS.supports&&CSS.supports("-webkit-line-clamp",
"1")?e:e.concat(Array.prototype.slice.call(a))).filter(function(b){return!!b.offsetParent}).map(function(b){var d=ra(b);d&&(d.truncate(),b.classList.add("p13n-sc-truncated"),b.classList.remove("p13n-sc-truncate"),b.classList.remove("p13n-sc-truncate-fallback"),b.className=b.className.replace(/p13n-sc-line-clamp-\d/g,""))})},ta=function(a){a.querySelectorAll(".a-carousel-viewport").forEach(function(e){e=e.querySelectorAll(".a-carousel-card");for(var b=null,d=0;d<e.length;d++){var c=e[d].getAttribute("aria-roledescription");
if(null!==c&&""!==c){b=c;break}}b=b||"slide";e.forEach(function(f){f.getAttribute("aria-roledescription")!==b&&f.setAttribute("aria-roledescription",b)})})},za={initCarousel:function(a){return q.__awaiter(void 0,void 0,void 0,function(){var e,b,d,c,f;return q.__generator(this,function(h){e=a||{};b=e.afterPageLoaded;d=e.afterDeliveryMessageLoaded;c=v["default"].cardRoot.classList.contains("p13n-sc-shoveler")?[v["default"].cardRoot]:Array.prototype.slice.call(v["default"].cardRoot.getElementsByClassName("p13n-sc-shoveler"));
f=I["default"].setup(["getCarouselItems"]);if(null===c||void 0===c||!c.length)return[2];c.forEach(function(k){return q.__awaiter(void 0,void 0,void 0,function(){var l,r,g,m,u,n;return q.__generator(this,function(t){switch(t.label){case 0:l=k.dataset||{};r="true"===l.showlazyloaddeliverymessage;g=function(){p["default"].loadDynamicImage("[data-name]='"+n+"' .p13n-sc-dynamic-image");sa(k);qa(k);null===b||void 0===b?void 0:b(k);ea();ta(k);r&&pa(k).then(function(){return null===d||void 0===d?void 0:d(k)})};
g();if(k.classList.contains("p13n-carousel-initialized"))return[2];k.classList.add("p13n-carousel-initialized");m=Z["default"].getCarousel(R.unscope(k));u=Y["default"].getCarousel(k);n=m.getAttr("name");return[4,Promise.all([u.initialized,ma.setupModal(k)])];case 1:return t.sent(),p["default"].on("a:carousel:"+n+":change:pageSize",g),p["default"].on("a:carousel:"+n+":change:loading",g),p["default"].on("a:carousel:"+n+":change:animating",g),p["default"].on("a:carousel:"+n+":change:fetchedItems",g),
u.attachRemoteOperation(function(A){var F=A.indexes;A=A.ids;var N=f,ua=N.getCarouselItems,va=q.__assign,wa=q.__assign({},l),xa=String(F[0]||0);var ya=F[0]||0,y,G,O=0,w=l.aCarouselOptions?l.aCarouselOptions:void 0;if(w&&(w=JSON.parse(w),w=null===(y=null===w||void 0===w?void 0:w.ajax)||void 0===y?void 0:y.id_list))for(y=0;y<ya&&y<w.length;y++){var B=JSON.parse(w[y]);"true"===((null===(G=null===B||void 0===B?void 0:B.metadataMap)||void 0===G?0:G.isSponsoredProduct)?B.metadataMap.isSponsoredProduct:"false")&&
(O+=1)}return ua.call(N,va.call(q,wa,{ids:A,indexes:F,offset:xa,adOffset:O}))}),[2]}})})});return[2]})})}};H._operationNames=["getCarouselItems"];H.card=function(){return q.__awaiter(void 0,void 0,void 0,function(){return q.__generator(this,function(a){switch(a.label){case 0:return[4,za.initCarousel()];case 1:return a.sent(),[2]}})})}});
